spring:
  application:
    name: demo-ci
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/democi?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC}"
    username: ${SPRING_DATASOURCE_USERNAME:democi}
    password: ${SPRING_DATASOURCE_PASSWORD:democi}
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
